In [ ]:
https://www.espncricinfo.com/records/highest-career-batting-average-282910

In [ ]:
#import pandas as pd

In [2]:
import pandas as pd

In [ ]:
#import csv

In [3]:
df = pd.read_csv('crickettestmatchdata.csv')

In [4]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,NaN,NaN,NaN
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,NaN,NaN,NaN
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,NaN,NaN,NaN
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,NaN,NaN,NaN
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,NaN,NaN,NaN
61,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,NaN,NaN,NaN
62,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,NaN,NaN,NaN
63,Hashmatullah Shahidi (AFG),2018-2025,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,NaN,NaN,NaN
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,NaN,NaN,NaN

In [ ]:
#rename muliple colums in a list

In [8]:

df = df.rename(columns = {'Mat':'Matches_Played','NO':'Not_Out','HS':'Highest_Inns_Score','Inns':'Innings_Batted','BF':'Balls_Faced','SR':'Batting_Strike_Rate'})

In [10]:
df.head()

,Player,Span,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,NaN,NaN,NaN
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,NaN,NaN,NaN
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,NaN,NaN,NaN
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,NaN,NaN,NaN
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,NaN,NaN,NaN

In [ ]:
#check null values

In [11]:
df.isnull().any()

Player                 False
Span                   False
Matches_Played         False
Innings_Batted         False
Not_Out                False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced            False
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
Unnamed: 15             True
Unnamed: 16             True
Unnamed: 17             True
dtype: bool

In [19]:
df = df.drop(['Unnamed: 15','Unnamed: 16','Unnamed: 17'], axis = 1)

In [21]:
df.head()

,Player,Span,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1

In [ ]:
#drop duplications

In [12]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
60    False
61    False
62    False
63    False
64    False
Length: 65, dtype: bool

In [13]:
df[df['Player'].duplicated()==1]

,Player,Span,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Unnamed: 15,Unnamed: 16,Unnamed: 17
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,NaN,NaN,NaN
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,NaN,NaN,NaN
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,NaN,NaN,NaN

In [14]:
df[df['Player'].isin(['GA Headley (WI)','GS Sobers (WI)','JB Hobbs (ENG)'])]

,Player,Span,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Unnamed: 15,Unnamed: 16,Unnamed: 17
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,NaN,NaN,NaN
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,NaN,NaN,NaN
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,NaN,NaN,NaN
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,NaN,NaN,NaN
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,NaN,NaN,NaN
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,NaN,NaN,NaN

In [17]:
df = df.drop_duplicates()

In [ ]:
#split up sapn into start and end date + career length

In [23]:
df['Span'].str.split(pat = '-')

0     [1928, 1948]
1     [2022, 2025]
2     [2015, 2016]
3     [1963, 1970]
4     [1930, 1954]
          ...
60    [2002, 2014]
61    [1924, 1934]
62    [1930, 1938]
63    [2018, 2025]
64    [1928, 1934]
Name: Span, Length: 62, dtype: object

In [26]:
df['Span'].str.split(pat = '-').str[0]

0     1928
1     2022
2     2015
3     1963
4     1930
      ...
60    2002
61    1924
62    1930
63    2018
64    1928
Name: Span, Length: 62, dtype: object

In [29]:
df['Rookie_year'] = df['Span'].str.split(pat = '-').str[0]

In [28]:
df['final_year'] = df['Span'].str.split(pat = '-').str[1]

In [30]:
df

,Player,Span,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie-year,final_year,Rookie_year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,1928
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,2022
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,2015
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,1963
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,2002
61,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,1924
62,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,1930
63,Hashmatullah Shahidi (AFG),2018-2025,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,2018,2025,2018
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,1928

In [ ]:
#drop span colums

In [32]:
df = df.drop(['Span','Rookie-year'], axis = 1)

In [34]:
df.head()

,Player,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1948,1928
1,PHKD Mendis (SL),14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2025,2022
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2016,2015
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1970,1963
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1954,1930

In [ ]:
#split up the country from player

In [37]:
df['Player'].str.split(pat = '(').str[1]

0        AUS)
1         SL)
2        AUS)
3         SA)
4         WI)
       ...
60    ICC/SA)
61       AUS)
62       AUS)
63       AFG)
64       ENG)
Name: Player, Length: 62, dtype: object

In [38]:
df['Country'] = df['Player'].str.split(pat = '(').str[1]

In [39]:
df['Player_name'] = df['Player'].str.split(pat = '(').str[0]

In [41]:
df.head()

,Player,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year,Country,Player_name
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1948,1928,AUS),DG Bradman
1,PHKD Mendis (SL),14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2025,2022,SL),PHKD Mendis
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2016,2015,AUS),AC Voges
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1970,1963,SA),RG Pollock
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1954,1930,WI),GA Headley

In [42]:
df = df.drop(['Player'], axis = 1)

In [43]:
df

,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year,Country,Player_name
0,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1948,1928,AUS),DG Bradman
1,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2025,2022,SL),PHKD Mendis
2,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2016,2015,AUS),AC Voges
3,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1970,1963,SA),RG Pollock
4,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1954,1930,WI),GA Headley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2014,2002,ICC/SA),GC Smith
61,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1934,1924,AUS),WH Ponsford
62,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1938,1930,AUS),SJ McCabe
63,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,2025,2018,AFG),Hashmatullah Shahidi
64,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1934,1928,ENG),DR Jardine

In [45]:
df['Country'].str.split(pat = '(').str[0]

0        AUS)
1         SL)
2        AUS)
3         SA)
4         WI)
       ...
60    ICC/SA)
61       AUS)
62       AUS)
63       AFG)
64       ENG)
Name: Country, Length: 62, dtype: object

In [46]:
df['Country'] = df['Country'].str.split(pat = ')').str[0]

In [47]:
df['Country']

0        AUS
1         SL
2        AUS
3         SA
4         WI
       ...
60    ICC/SA
61       AUS
62       AUS
63       AFG
64       ENG
Name: Country, Length: 62, dtype: object

In [48]:
df

,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year,Country,Player_name
0,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1948,1928,AUS,DG Bradman
1,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2025,2022,SL,PHKD Mendis
2,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2016,2015,AUS,AC Voges
3,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1970,1963,SA,RG Pollock
4,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1954,1930,WI,GA Headley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2014,2002,ICC/SA,GC Smith
61,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1934,1924,AUS,WH Ponsford
62,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1938,1930,AUS,SJ McCabe
63,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,2025,2018,AFG,Hashmatullah Shahidi
64,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1934,1928,ENG,DR Jardine

In [ ]:
#change datatypes

In [49]:
df.dtypes

Matches_Played           int64
Innings_Batted           int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
final_year              object
Rookie_year             object
Country                 object
Player_name             object
dtype: object

In [51]:
df['Highest_Inns_Score'].str.split(pat = '*')

0       [334]
1     [182, ]
2     [269, ]
3       [274]
4     [270, ]
       ...
60      [277]
61      [266]
62      [232]
63      [246]
64      [127]
Name: Highest_Inns_Score, Length: 62, dtype: object

In [52]:
df['Highest_Inns_Score'].str.split(pat = '*').str[0]

0     334
1     182
2     269
3     274
4     270
     ...
60    277
61    266
62    232
63    246
64    127
Name: Highest_Inns_Score, Length: 62, dtype: object

In [53]:
df['Highest_Inns_Score'] = df['Highest_Inns_Score'].str.split(pat = '*').str[0]

In [54]:
df

,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year,Country,Player_name
0,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1948,1928,AUS,DG Bradman
1,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,2025,2022,SL,PHKD Mendis
2,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2016,2015,AUS,AC Voges
3,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1970,1963,SA,RG Pollock
4,22,40,4,2190,270,60.83,416+,56,10,5,2,104+,1,1954,1930,WI,GA Headley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2014,2002,ICC/SA,GC Smith
61,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1934,1924,AUS,WH Ponsford
62,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1938,1930,AUS,SJ McCabe
63,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,2025,2018,AFG,Hashmatullah Shahidi
64,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1934,1928,ENG,DR Jardine

In [ ]:
df['Highest_Inns_Score'].astype('int')

In [55]:
df['Highest_Inns_Score'] = df['Highest_Inns_Score'].astype('int')

In [56]:
df.dtypes

Matches_Played           int64
Innings_Batted           int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
final_year              object
Rookie_year             object
Country                 object
Player_name             object
dtype: object

In [59]:
df = df.astype({'final_year':'int','Rookie_year':'int'})

In [62]:
df.dtypes

Matches_Played           int64
Innings_Batted           int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
final_year               int64
Rookie_year              int64
Country                 object
Player_name             object
dtype: object

In [63]:
df['Balls_Faced'] = df['Balls_Faced'].str.split(pat = '+').str[0]

In [64]:
df['Balls_Faced'] = df['Balls_Faced'].astype('int')

ValueError: invalid literal for int() with base 10: '-'

In [65]:
df[df'Balls_Faced'].isna()==1

SyntaxError: invalid syntax (266422172.py, line 1)

In [66]:
df[df'Balls_Faced'].isna('-')==1

SyntaxError: invalid syntax (292528407.py, line 1)

In [68]:
df['Balls_Faced'] = (
    df['Balls_Faced']
    .astype(str)
    .str.strip()
    .replace('-', '0')
)

df['Balls_Faced'] = df['Balls_Faced'].astype(int)

In [69]:
df.dtypes

Matches_Played           int64
Innings_Batted           int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced              int64
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
final_year               int64
Rookie_year              int64
Country                 object
Player_name             object
dtype: object

In [71]:
df['Batting_Strike_Rate'] = df['Batting_Strike_Rate'].astype('float')

ValueError: could not convert string to float: '-'

In [72]:
df['Batting_Strike_Rate'] = (
    df['Batting_Strike_Rate']
    .astype(str)
    .str.strip()
    .replace('-', '0')
)

df['Batting_Strike_Rate'] = df['Batting_Strike_Rate'].astype(float)

In [73]:
df.dtypes

Matches_Played           int64
Innings_Batted           int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced              int64
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
final_year               int64
Rookie_year              int64
Country                 object
Player_name             object
dtype: object

In [74]:
df = df.astype({'4s':'int','6s':'int'})

ValueError: invalid literal for int() with base 10: '626+': Error while type casting for column '4s'

In [75]:
df['4s'] = df['4s'].str.split(pat = '+').str[0]

In [76]:
df['6s'] = df['6s'].str.split(pat = '+').str[0]

In [77]:
df['4s'] = df['4s'].astype('int')

In [78]:
df['6s'] = df['6s'].astype('int')

In [79]:
df.dtypes

Matches_Played           int64
Innings_Batted           int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced              int64
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
final_year               int64
Rookie_year              int64
Country                 object
Player_name             object
dtype: object

In [80]:
df

,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year,Country,Player_name
0,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1948,1928,AUS,DG Bradman
1,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,2025,2022,SL,PHKD Mendis
2,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2016,2015,AUS,AC Voges
3,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1970,1963,SA,RG Pollock
4,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1954,1930,WI,GA Headley
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2014,2002,ICC/SA,GC Smith
61,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1934,1924,AUS,WH Ponsford
62,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1938,1930,AUS,SJ McCabe
63,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,2025,2018,AFG,Hashmatullah Shahidi
64,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1934,1928,ENG,DR Jardine

In [81]:
#career lenghth colum how log a playeer played

In [82]:
df['Career_Length'] = df['final_year'] - df['Rookie_year']

In [83]:
df

,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year,Country,Player_name,Career_Length
0,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1948,1928,AUS,DG Bradman,20
1,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,2025,2022,SL,PHKD Mendis,3
2,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2016,2015,AUS,AC Voges,1
3,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1970,1963,SA,RG Pollock,7
4,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1954,1930,WI,GA Headley,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2014,2002,ICC/SA,GC Smith,12
61,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1934,1924,AUS,WH Ponsford,10
62,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1938,1930,AUS,SJ McCabe,8
63,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,2025,2018,AFG,Hashmatullah Shahidi,7
64,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1934,1928,ENG,DR Jardine,6

In [84]:
#average career length

In [85]:
df['Career_Length'].mean()

np.float64(13.129032258064516)

In [88]:
import numpy as np

value = np.float64(13.129032258064516)

print(round(value, 2))

13.13

In [ ]:
#average batting strike rate for cricketers who played over 10 years

In [89]:
df[df['Career_Length'] > 10 ]

,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year,Country,Player_name,Career_Length
0,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1948,1928,AUS,DG Bradman,20
4,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1954,1930,WI,GA Headley,24
6,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1935,1924,ENG,H Sutcliffe,11
8,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1968,1955,ENG,KF Barrington,13
10,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1947,1927,ENG,WR Hammond,20
11,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1974,1954,WI,GS Sobers,20
13,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2015,2000,SL,KC Sangakkara,15
14,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1930,1908,ENG,JB Hobbs,22
16,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1960,1948,WI,CL Walcott,12
17,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1955,1937,ENG,L Hutton,18
18,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2026,2010,AUS,SPD Smith,16
19,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,2013,1995,ICC/SA,JH Kallis,18
22,108,192,19,9461,251,54.68,18198,51.98,33,38,11,1056,28,2025,2010,NZ,KS Williamson,15
25,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1984,1970,AUS,GS Chappell,14
26,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1951,1935,SA,AD Nourse,16
27,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,2013,1989,IND,SR Tendulkar,24
28,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,2006,1990,ICC/WI,BC Lara,16
29,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1993,1976,PAK,Javed Miandad,17
30,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,2012,1996,ICC/IND,R Dravid,16
31,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,2010,1998,PAK,Mohammad Yousuf,12
32,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2017,2000,PAK,Younis Khan,17
33,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,2012,1995,AUS,RT Ponting,17
37,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,2015,1994,WI,S Chanderpaul,21
38,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1987,1971,IND,SM Gavaskar,16
39,163,298,25,13943,262,51.07,24242,57.51,41,66,15,1492,46,2026,2012,ENG,JE Root,14
40,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,2004,1985,AUS,SR Waugh,19
41,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,2009,1994,AUS,ML Hayden,15
42,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2018,2004,SA,AB de Villiers,14
43,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1994,1978,AUS,AR Border,16
44,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1991,1974,WI,IVA Richards,17
45,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1957,1937,ENG,DCS Compton,20
46,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,2014,1997,SL,DPMD Jayawardene,17
47,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,2007,1992,ICC/PAK,Inzamam-ul-Haq,15
48,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1963,1948,WI,FMM Worrell,15
49,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1928,1911,ENG,CP Mead,17
50,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2013,2001,ICC/IND,V Sehwag,12
53,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2015,2004,AUS,MJ Clarke,11
55,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1949,1929,SA,B Mitchell,20
56,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,1905,1893,ENG,Hon.FS Jackson,12
57,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2013,2001,SL,TT Samaraweera,12
58,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1963,1948,AUS,RN Harvey,15
59,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1981,1965,AUS,KD Walters,16
60,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2014,2002,ICC/SA,GC Smith,12

In [90]:
df[df['Career_Length'] > 10 ]['Batting_Strike_Rate'].mean()

np.float64(47.8153488372093)

In [91]:
value = np.float64(47.8153488372093)

print(round(value, 2))

47.82

In [92]:
#players who played before 1960

In [103]:
df[df['Rookie_year'] < 1960 ]

,Matches_Played,Innings_Batted,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,final_year,Rookie_year,Country,Player_name,Career_Length
0,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1948,1928,AUS,DG Bradman,20
4,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1954,1930,WI,GA Headley,24
6,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1935,1924,ENG,H Sutcliffe,11
7,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1939,1931,ENG,E Paynter,8
8,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1968,1955,ENG,KF Barrington,13
9,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1958,1948,WI,ED Weekes,10
10,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1947,1927,ENG,WR Hammond,20
11,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1974,1954,WI,GS Sobers,20
14,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1930,1908,ENG,JB Hobbs,22
16,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1960,1948,WI,CL Walcott,12
17,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1955,1937,ENG,L Hutton,18
20,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1929,1921,ENG,GE Tyldesley,8
26,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1951,1935,SA,AD Nourse,16
34,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1929,1920,AUS,J Ryder,9
45,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1957,1937,ENG,DCS Compton,20
48,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1963,1948,WI,FMM Worrell,15
49,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1928,1911,ENG,CP Mead,17
55,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1949,1929,SA,B Mitchell,20
56,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,1905,1893,ENG,Hon.FS Jackson,12
58,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1963,1948,AUS,RN Harvey,15
61,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1934,1924,AUS,WH Ponsford,10
62,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1938,1930,AUS,SJ McCabe,8
64,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1934,1928,ENG,DR Jardine,6

In [100]:
df[df['Rookie_year'] < 1960 ]['Player_name'].count()

np.int64(23)

In [102]:
value = np.int64(23)

print(int(value))

23

In [93]:
#highest innings score by country

In [104]:
df.groupby('Country')['Highest_Inns_Score'].max()

Country
AFG        246
AUS        380
ENG        364
ICC/IND    319
ICC/PAK    329
ICC/SA     277
ICC/WI     400
IND        248
NZ         251
PAK        313
SA         278
SL         374
WI         365
ZIM        232
Name: Highest_Inns_Score, dtype: int64

In [107]:
df.groupby('Country')['Highest_Inns_Score'].max().to_frame('highscorecountry').reset_index().sort_values('highscorecountry', ascending = False)

    Country  highscorecountry
6    ICC/WI               400
1       AUS               380
11       SL               374
12       WI               365
2       ENG               364
4   ICC/PAK               329
3   ICC/IND               319
9       PAK               313
10       SA               278
5    ICC/SA               277
8        NZ               251
7       IND               248
0       AFG               246
13      ZIM               232